---
- name: Create default security group
  hosts: localhost
  
  vars:
    region: us-east-1
  
  tasks:
  - name: create group
    ec2_group:
      name: default-ansible-group 
      description: Security Group for EC2 Server
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: basic_firewall

- name: create new build instance
  hosts: localhost

  vars:
    keypair: ansible_aws_key
    security_group: default ansible group
    image: ami-08d4ac5b634553e16
    instance_type: t2.micro
    region: us-east-1

  tasks:
  - name: launch instance
    ec2:
      profile: avasekho
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      region: "{{ region }}"
      instance_tags:
        name: "build_server"
      network:
          assign_public_ip: true
      volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 8
          delete_on_termination: true
    register: ec2_build

  - name: add instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: build
    loop: "{{ ec2_build.instances }}"